### ISSUE TITLE
JAVACV TEST NOT WORKING

### ISSUE THREAD

**Issue by harpreet-singh-bola** [gderaco/JavaCVTest#1]
Hello Sir, I need your help on your project JavaCV Test in which I am interested. I didn't find any your contact so i decided to contact you with "Issues".

I am running the project on Android Studio, and I am getting the following error:

"Error:(34, 25) error: no suitable method found for record(IplImage)
method FrameRecorder.record(Frame) is not applicable
(argument mismatch; IplImage cannot be converted to Frame)
method FFmpegFrameRecorder.record(Frame) is not applicable
(argument mismatch; IplImage cannot be converted to Frame)
method FFmpegFrameRecorder.record(AVFrame) is not applicable
(argument mismatch; IplImage cannot be converted to AVFrame)"

Can you please help me?

Thank you,
with regards,
SHP.

**Comment by lancevalour** [comment]
It is not working.

**Comment by gderaco** [comment]
using `compile 'org.bytedeco:javacv:0.10'`
instead of `compile 'org.bytedeco:javacv:+'`
should fix the issue
